version: '3.8'
services:
  app:
    image: "ghcr.io/yellow-dog-man/go.resonite.com:main"
    container_name: go.resonite.com
    build: .
    ports:
      - "3002:3000"
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production